'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {BookOpen,LockKeyhole} from 'lucide-react';
export async function authRequest(x:any){const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d}
export function AuthGate({children}:any){const [user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/auth',{cache:'no-store'}).then(async r=>{if(r.ok)setUser(await r.json());else if(r.status!==401)setError('서버에 연결하지 못했습니다. 새로고침해 주세요.')}).catch(()=>setError('서버에 연결하지 못했습니다.')).finally(()=>setReady(true))},[]);
 if(!ready)return <main className="auth-wrap"><p>로그인 상태 확인 중…</p></main>;
 if(user)return children(user,()=>{setUser(null);setMode('login');setError('')});
 return <main className="auth-wrap"><section className="panel auth-card"><div className="brand"><span className="brand-mark"><BookOpen/></span>플랜두씨</div><h1>{mode==='login'?'내 기록에 로그인':'내 계정 만들기'}</h1><p className="muted">계획과 실제 기록은 로그인한 본인에게만 보입니다.</p><form className="edit-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const v=Object.fromEntries(new FormData(e.currentTarget));try{await authRequest({...v,action:mode});if(mode==='register'){setMode('login');setError('가입했습니다. 같은 아이디로 로그인해 주세요.')}else{const r=await fetch('/api/auth',{cache:'no-store'});if(!r.ok)throw new Error('로그인을 확인하지 못했습니다.');setUser(await r.json())}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">아이디<input name="username" autoComplete="username" required pattern="[a-zA-Z0-9_-]{4,40}" minLength={4} maxLength={40} placeholder="영문·숫자·밑줄·하이픈 4~40자"/></label><label className="field">비밀번호<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='register'?12:1} placeholder="12자 이상 · UTF-8 72바이트 이하"/></label>{error&&<p role="status" className="setup-inline">{error}</p>}<button className="button primary" disabled={busy}>{busy?'처리 중…':mode==='login'?'로그인':'가입하기'}</button></form><button className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'처음 오셨나요? 계정 만들기':'이미 계정이 있나요? 로그인'}</button><p className="small-note"><LockKeyhole size={14}/> 12시간 후 자동 만료 · 비밀번호 재설정은 아직 지원하지 않습니다. 비밀번호를 채팅이나 제출물에 적지 마세요.</p></section></main>
}
export function AccountPanel({user,onExit}:any){const [open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('password');return <><button className="button light" onClick={()=>setOpen(true)}>내 계정</button><button className="button light" disabled={busy} onClick={async()=>{setBusy(true);try{await authRequest({action:'logout'});onExit()}catch(e){setError((e as Error).message);setOpen(true)}finally{setBusy(false)}}}>로그아웃</button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>내 계정 · {user.username}</DialogTitle><DialogDescription>비밀번호 변경 시 모든 로그인 세션이 종료됩니다. 계정을 삭제하면 내 계획·할 일·실행·관찰 기록도 함께 삭제됩니다. 먼저 전체 내보내기로 보관하세요.</DialogDescription></DialogHeader><div className="form-actions"><button className="button light" onClick={()=>setMode('password')}>비밀번호 변경</button><button className="button danger" onClick={()=>setMode('delete-account')}>계정 삭제</button></div><form className="edit-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const v=Object.fromEntries(new FormData(e.currentTarget));try{await authRequest({...v,action:mode});onExit()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">현재 비밀번호<input name="current_password" type="password" autoComplete="current-password" required/></label>{mode==='password'?<label className="field">새 비밀번호<input name="new_password" type="password" autoComplete="new-password" required minLength={12}/></label>:<label><input type="checkbox" required/> 내 계정과 연결된 모든 자료를 삭제하는 데 동의합니다.</label>}{error&&<p role="alert">{error}</p>}<button disabled={busy} className={'button '+(mode==='password'?'primary':'danger')}>{busy?'처리 중…':mode==='password'?'변경 후 모든 기기 로그아웃':'계정과 내 자료 영구 삭제'}</button></form></DialogContent></Dialog></>}
