'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function ObservationPanel({tasks}:any){const [data,setData]=useState<any>({days:[],rules:null,spec:{}}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[cancelOpen,setCancelOpen]=useState(false),[excludeOpen,setExcludeOpen]=useState(false);
 const eligible=tasks.filter((t:any)=>!t.deleted_at&&t.status==='open'&&t.expected_minutes!=null);
 const eligibleIds=eligible.map((t:any)=>t.id).sort().join('|');
 const selectedEligible=selected.filter(id=>eligible.some((t:any)=>t.id===id));
 useEffect(()=>{setSelected(prev=>prev.filter(id=>eligible.some((t:any)=>t.id===id)))},[eligibleIds]);
 const refresh=()=>fetch('/api/observations',{cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d)});
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 async function send(x:any){setBusy(true);setError('');try{const r=await fetch('/api/observations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);await refresh();setSelected([]);setCancelOpen(false);setExcludeOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const days=data.days||[],active=days.find((d:any)=>!d.finished_at),change=data.rules?.change_json?JSON.parse(data.rules.change_json):null;
 const stats=(ds:any[])=>{const v=ds.filter(d=>d.finished_at&&d.metric!=null);const sum=v.reduce((s,d)=>s+d.metric,0);return `${v.length}일 · 합계 ${sum}분 · 평균 ${v.length?(sum/v.length).toFixed(1):'—'}분`};
 return <section className="panel observation-panel"><p className="eyebrow">실제 5일 관찰</p><h2>예상과 실제의 간격 좁히기</h2><p>{data.spec.question}</p><details><summary>고정한 지표와 계산 규칙</summary><p>{data.spec.metric} · {data.spec.unit}</p><p>{data.spec.calculation}</p><p>변경 전: {data.spec.before}</p><p>시간대: Asia/Seoul · 주 시작: 월요일</p></details>{error&&<p role="alert" className="error-banner">{error}</p>}
 <div className="two-cols"><div className="insight"><b>변경 전 · 1~2일차</b><p>{stats(days.filter((d:any)=>d.ordinal<=2))}</p></div><div className="insight"><b>변경 후 · 3~5일차</b><p>{stats(days.filter((d:any)=>d.ordinal>=3))}</p></div></div>
 {days.map((d:any)=><details className="log-detail" key={d.id}><summary>{d.ordinal}일차 · {d.date} · {d.finished_at?(d.metric==null?'누락 · 계산 제외':`절대 차이 ${d.metric}분`):'관찰 중'}</summary><p>예상 {d.expected}분 / 실제 {d.actual==null?'미확정':d.actual+'분'}</p><p>시작: {new Date(d.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><ul>{JSON.parse(d.baseline).map((t:any)=><li key={t.id}>{t.title} · {t.expected_minutes}분</li>)}</ul>{d.note&&<p>{JSON.parse(d.note).text}</p>}</details>)}
 {active?<form className="edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:'finish',id:active.id,note:f.get('note'),missing:f.get('missing')==='on'})}}><h3>{active.ordinal}일차 마감</h3><p>하루의 관찰 대상 작업을 끝낸 뒤 마감하세요. 오늘의 연결된 실행 기록을 합산하고 그 시점의 근거를 보존합니다. 마감 후 수정하지 않습니다.</p><label className="field">확인 결과<textarea name="note" required maxLength={3000} placeholder="작업하지 않은 항목, 누락·중복 여부, 유난히 큰 값의 이유를 적으세요."/></label><label><input name="missing" type="checkbox"/> 시간을 알 수 없는 누락이 있어 오늘 지표를 계산에서 제외합니다.</label><label><input type="checkbox" required/> 오늘 기록의 중복 여부를 확인했고, 실행 기록이 없는 대상은 미작업 0분이거나 위의 누락으로 표시했습니다.</label><button className="button primary" disabled={busy}>오늘 관찰 마감</button><button type="button" className="button light" disabled={busy} onClick={()=>setCancelOpen(true)}>작업 전 선택 실수로 취소</button><button type="button" className="button light" disabled={busy} onClick={()=>setExcludeOpen(true)}>시작 순서 오류로 관찰 제외</button></form>:days.length===2&&!change?<form className="edit-form" onSubmit={e=>{e.preventDefault();send({action:'change',...Object.fromEntries(new FormData(e.currentTarget))})}}><h3>3일차 시작 전, 규칙 하나 변경</h3><p>위 1·2일차 기록을 검토한 뒤 작성하세요. 변경 시각과 두 기록의 ID가 함께 저장됩니다.</p><label className="field">새 계획 규칙<textarea name="rule" required maxLength={2000}/></label><label className="field">1·2일차 결과에 근거한 변경 이유<textarea name="reason" required maxLength={2000}/></label><button className="button primary" disabled={busy}>규칙 변경 기록</button></form>:days.length<5?<div className="edit-form"><h3>{days.length+1}일차 시작 준비</h3><p>오늘 실제 작업을 시작하기 전에 대상과 예상 시간을 확정하세요. 이전 날짜로 소급 입력할 수 없습니다.</p><div className="observation-tasks">{eligible.map((t:any)=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/>{t.title} · {t.expected_minutes}분</label>)}</div><p><b>선택한 대상: {selectedEligible.length}개 · 예상 {eligible.filter((t:any)=>selectedEligible.includes(t.id)).reduce((s:number,t:any)=>s+t.expected_minutes,0)}분</b></p><button className="button primary" disabled={busy||!selectedEligible.length} onClick={()=>send({action:'start',task_ids:selectedEligible})}>오늘 대상 확정하고 관찰 시작</button></div>:<p className="insight">5일 기록을 마쳤습니다. 전체 내보내기로 기록과 전후 비교 근거를 보관하세요.</p>}
 {change&&<div className="insight"><b>변경한 규칙</b><p>{change.rule}</p><p>이유: {change.reason}</p><small>{new Date(change.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div>}{data.cancellations?.length>0&&<details><summary>취소·제외 이력 {data.cancellations.length}건 · 5일 집계 제외</summary>{data.cancellations.map((c:any)=>{const old=JSON.parse(c.original_json);return <div className="log-detail" key={c.id}><b>{old.ordinal}일차 {old.exclusion_kind==='start_order'?'시작 순서 오류로 제외':'시작 취소'} · {old.date} · 예상 {old.expected}분</b><p>{c.reason}</p>{old.exclusion_kind==='start_order'&&<><p>실행 기록은 변경하지 않았습니다. 관찰 시작: {new Date(old.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><ul>{old.log_snapshot?.map((l:any)=><li key={l.id}>실제 시작 {new Date(l.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · {l.actual_minutes}분</li>)}</ul></>}<small>{new Date(c.cancelled_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div>})}</details>}
 <Dialog open={cancelOpen} onOpenChange={setCancelOpen}><DialogContent><DialogHeader><DialogTitle>잘못 선택한 관찰 시작을 취소할까요?</DialogTitle><DialogDescription>아직 실제 작업을 시작하지 않았고 연결된 실행 기록이 없을 때만 가능합니다. 시작 시각·대상·예상 시간과 취소 사유는 이력과 전체 내보내기에 보존됩니다. 다시 시작하면 새로운 시작 시각으로 기록됩니다.</DialogDescription></DialogHeader><form className="edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:'cancel',id:active?.id,reason:f.get('reason'),before_work:f.get('before_work')==='on'})}}><label className="field">취소 사유<textarea name="reason" required maxLength={2000}/></label><label><input name="before_work" type="checkbox" required/> 아직 관찰 대상의 실제 작업을 시작하지 않았으며, 선택 실수를 바로잡기 위한 취소입니다.</label>{error&&<p role="alert" className="error-banner">{error}</p>}<button className="button primary" disabled={busy}>이력을 남기고 시작 취소</button></form></DialogContent></Dialog>
 <Dialog open={excludeOpen} onOpenChange={setExcludeOpen}><DialogContent><DialogHeader><DialogTitle>시작 순서 오류로 관찰 제외</DialogTitle><DialogDescription>실제 작업을 먼저 시작하고 나중에 관찰 대상을 확정한 경우입니다. 서버가 시작 시각을 비교해 확인합니다. 실제 실행 기록·완료 상태는 그대로 두고, 관찰 원본과 실행 근거·제외 사유를 이력에 보존합니다. 마감된 관찰은 제외할 수 없습니다.</DialogDescription></DialogHeader><form className="edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:'exclude-order',id:active?.id,reason:f.get('reason'),preserve_records:f.get('preserve_records')==='on'})}}><label className="field">제외 사유<textarea name="reason" required maxLength={2000} placeholder="실제 작업 시작과 관찰 대상 확정의 순서가 어긋난 경위를 적어 주세요."/></label><label><input name="preserve_records" type="checkbox" required/> 실제 작업 시각과 소요 시간은 그대로 보존하고, 사전 계획이 성립하지 않은 이 관찰만 5일 집계에서 제외합니다.</label>{error&&<p role="alert" className="error-banner">{error}</p>}<p>제외 후에는 아직 시작하지 않은 새 작업을 선택해 관찰을 시작하세요. 이미 작업한 시간을 새 관찰로 옮기지 않습니다.</p><button className="button primary" disabled={busy}>실제 기록을 보존하고 관찰 제외</button></form></DialogContent></Dialog>
 </section>
}
