'use client';
import {useEffect,useState,useMemo} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {Plus,Download,RefreshCw,ArrowUpRight,BookOpen,Check,Clock3,History,CalendarDays,Pencil,Trash2,Undo2,Search,ChevronRight,Layers,Target,ListChecks,NotebookPen,ChartNoAxesCombined} from 'lucide-react';
import {aggregate,type Row} from '@/lib/pds-service';
const empty={plans:[],tasks:[],logs:[],completions:[],reflections:[],revisions:[],today:'',timezone:'Asia/Seoul',unit:'minutes'};
const priorityNames:Row={high:'높음',medium:'보통',low:'낮음'};
function Pick({name,value,onChange,items,label,defaultValue}:any){return <Select name={name} value={value} defaultValue={defaultValue} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(([v,l]:string[])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
const priorityItems=[['high','높음'],['medium','보통'],['low','낮음']];
function Field({label,children}:any){return <label className="field"><span>{label}</span>{children}</label>}
function localTime(iso:string){if(!iso)return '—';return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short',hour12:false}).format(new Date(iso))}
function localInput(iso:string){return new Date(Date.parse(iso)+9*3600000).toISOString().slice(0,16)}
function hours(n:number){return `${Math.floor(n/60)}시간 ${n%60}분`}
export default function Home(){
 const [data,setData]=useState<Row>(empty),[selected,setSelected]=useState(''),[tab,setTab]=useState('do'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [dialog,setDialog]=useState<Row|null>(null),[remove,setRemove]=useState<Row|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[prio,setPrio]=useState('all'),[tag,setTag]=useState(''),[sort,setSort]=useState('due'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [logStart,setLogStart]=useState(''),[logEnd,setLogEnd]=useState(''),[requestKey,setRequestKey]=useState('');
 async function refresh(){const r=await fetch('/api/pds',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setSelected(prev=>d.plans.some((p:Row)=>p.id===prev)?prev:d.plans[0]?.id||'');return d}
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/pds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'bootstrap'})});if(!r.ok)throw new Error(((await r.json()) as any).error);await refresh()}catch(e){setError(String((e as Error).message))}finally{setLoading(false)}})()},[]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const life=new AbortController();Promise.resolve(mc.registerTool({name:'read_plan_do_see',title:'계획과 실행 기록 읽기',description:'현재 서버의 계획·할 일·실행 기록과 선택된 계획 집계를 읽습니다. 저장하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('빈 객체를 입력해 주세요.');const d=await refresh();return {plans:d.plans,tasks:d.tasks.filter((t:Row)=>!t.deleted_at),logs:d.logs,reflections:d.reflections}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 async function action(payload:Row,close=true){if(saving)return;setSaving(true);setError('');try{const r=await fetch('/api/pds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const res:any=await r.json();if(!r.ok)throw new Error(res.error);await refresh();if(close)setDialog(null);toast.success('서버에 저장했습니다.');return res}catch(e){setError((e as Error).message);toast.error((e as Error).message)}finally{setSaving(false)}}
 const plan=data.plans.find((p:Row)=>p.id===selected);const summary=useMemo(()=>aggregate(data,selected,from,to),[data,selected,from,to]);
 const allTasks=data.tasks.filter((t:Row)=>!t.deleted_at&&t.plan_id===selected);
 const visible=allTasks.filter((t:Row)=>{const text=(t.title+' '+JSON.parse(t.tags).join(' ')).toLowerCase();return text.includes(query.toLowerCase())&&(filter==='all'||filter==='done'&&t.status==='done'||filter==='open'&&t.status==='open'||filter==='late'&&t.status==='open'&&t.due_date&&t.due_date<data.today||filter==='blocked'&&data.logs.some((l:Row)=>l.task_id===t.id&&l.blocker.trim()))&&(prio==='all'||t.priority===prio)&&(!tag||JSON.parse(t.tags).some((s:string)=>s.toLowerCase().includes(tag.toLowerCase()))) }).sort((a:Row,b:Row)=>{let n=0;if(sort==='due')n=(a.due_date||'9999').localeCompare(b.due_date||'9999');if(sort==='priority')n=({high:0,medium:1,low:2}[a.priority as 'high']??3)-({high:0,medium:1,low:2}[b.priority as 'high']??3);if(sort==='created')n=a.created_at.localeCompare(b.created_at);return n||a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)});
 const sortedLogs=data.logs.filter((l:Row)=>allTasks.some((t:Row)=>t.id===l.task_id)).sort((a:Row,b:Row)=>b.started_at.localeCompare(a.started_at)||a.id.localeCompare(b.id));
 function openLog(t:Row){const end=new Date().toISOString();setLogEnd(localInput(end));setLogStart(localInput(end));setRequestKey(crypto.randomUUID());setDialog({kind:'log',item:t})}
 function exportAll(){const body=JSON.stringify({schema_version:2,exported_at:new Date().toISOString(),...data},null,2);const url=URL.createObjectURL(new Blob([body],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='plan-do-see-'+data.today+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function submit(e:any){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const d=dialog!;let payload:Row={...values};if(d.kind==='plan')payload={...payload,action:d.item?'plan-update':'plan-create',id:d.item?.id||d.newId,version:d.item?.version};if(d.kind==='task')payload={...payload,action:d.item?'task-update':'task-create',id:d.item?.id||d.newId,plan_id:selected};if(d.kind==='log')payload={...payload,action:'log',task_id:d.item.id,started_at:logStart+':00+09:00',ended_at:logEnd+':00+09:00',request_key:requestKey,complete:values.finish==='yes'};if(d.kind==='reflect')payload={...payload,action:'reflect',source_plan_id:selected,id:d.newId,reflection_id:d.reflectionId};const res=await action(payload);if(res?.id&&(d.kind==='plan'||d.kind==='reflect')){setSelected(res.id);setTab('plan')}}
 function taskView(t:Row){return <button className="task-name" onClick={()=>setDialog({kind:'detail',item:t})}>{t.title}<ChevronRight size={15}/></button>}
 const tabNames=[['plan','Plan','계획',Target],['do','Do','실행',NotebookPen],['see','See','돌아보기',ChartNoAxesCombined]];
 return <div className="app-shell"><Toaster richColors position="top-center"/><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><BookOpen size={23}/></span><span>플랜두씨<span className="brand-caption">나의 계획과 실제 사이</span></span></a><div className="top-actions"><span className="timezone">Asia/Seoul · 분 단위</span><button className="button light" onClick={exportAll} disabled={loading}><Download size={16}/>전체 내보내기</button></div></header>
 <main><div className="public-notice"><span>공개 다이어리</span><p>지금은 로그인이 없어 링크를 아는 사람은 누구나 볼 수 있습니다. 남이 봐도 괜찮은 내용만 넣으세요</p></div>
 <div className="page-heading"><div><p className="eyebrow">PLAN · DO · SEE</p><h1>계획은 선명하게,<br className="mobile-only"/> 기록은 솔직하게.</h1></div><div className="date-label"><CalendarDays size={19}/><span>{data.today||'날짜 불러오는 중'}</span><button className="icon-button" aria-label="서버 기록 새로고침" onClick={()=>refresh().then(()=>toast.success('서버 기록을 다시 불러왔습니다.')).catch(e=>setError(e.message))}><RefreshCw size={16}/></button></div></div>
 {error&&<div role="alert" className="error-banner">{error}</div>}
 {loading?<div className="empty-panel">서버에 저장된 기록을 불러오는 중입니다…</div>:<>
 <div className="plan-switch"><div className="select-plan"><Layers size={18}/><Pick label="계획 선택" value={selected||undefined} onChange={setSelected} items={data.plans.map((p:Row)=>[p.id,p.title+(p.draft?' · 작성 전':'')])}/></div><button className="button primary" onClick={()=>setDialog({kind:'plan',newId:crypto.randomUUID()})}><Plus size={17}/>새 계획</button></div>
 {plan?.draft===1&&<div className="setup-note"><div><b>실행 기록 3건을 가져왔습니다. 이제 실제 계획을 채워주세요.</b><p>제공하지 않은 계획·마감일·예상 시간은 비워 두었습니다. 계획을 입력하고, 실제 할 일을 2개 이상 추가할 수 있습니다.</p></div><button className="button light" onClick={()=>setDialog({kind:'plan',item:plan})}>계획 입력</button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs">{tabNames.map(([key,en,ko,Icon]:any)=><TabsTrigger className="main-tab" key={key} value={key}><Icon size={18}/><b>{en}</b><span>{ko}</span></TabsTrigger>)}</TabsList>
 <TabsContent value="plan"><div className="plan-layout"><section className="panel plan-main"><div className="section-title"><div><p className="eyebrow">지금 집중할 계획</p><h2>{plan?.title||'첫 계획을 만들어 보세요'}</h2></div>{plan&&<button className="icon-button" aria-label="계획 수정" onClick={()=>setDialog({kind:'plan',item:plan})}><Pencil size={18}/></button>}</div>{plan&&<><div className="plan-meta"><span><CalendarDays size={17}/>{plan.start_date||'시작일 미입력'} — {plan.end_date||'종료일 미입력'}</span><span className={'pill '+(plan.priority||'')}>{priorityNames[plan.priority]||'우선순위 미입력'}</span></div><h3>성공 기준</h3><p className="success-text">{plan.success||'어떤 상태가 되면 이 계획을 달성한 것인지 입력해 주세요.'}</p><div className="plan-bottom"><div><span className="muted">계획 전체 예상</span><strong>{plan.expected_minutes==null?'미입력':plan.expected_minutes+'분'}</strong></div><div><span className="muted">연결된 할 일</span><strong>{allTasks.length}개</strong></div><div><span className="muted">계획 버전</span><strong>v{plan.version}</strong></div></div>{plan.origin_reflection&&<div className="insight"><b>이전 돌아보기에서 가져온 한 줄</b><p>{data.reflections.find((r:Row)=>r.id===plan.origin_reflection)?.insight}</p></div>}</>}</section><section className="panel"><div className="section-title"><h2>수정 이력</h2><History size={18}/></div><p className="muted">수정해도 처음 계획은 남아 있습니다.</p><div className="history-list">{data.revisions.filter((r:Row)=>r.plan_id===selected).sort((a:Row,b:Row)=>b.version-a.version).map((r:Row)=>{const s=JSON.parse(r.snapshot);return <details key={r.id}><summary><span className="version">v{r.version}</span><span>{localTime(r.created_at)}</span></summary><dl><dt>제목</dt><dd>{s.title}</dd><dt>기간</dt><dd>{s.start_date||'미입력'} ~ {s.end_date||'미입력'}</dd><dt>성공 기준</dt><dd>{s.success||'미입력'}</dd><dt>우선순위 / 예상</dt><dd>{priorityNames[s.priority]||'미입력'} / {s.expected_minutes==null?'미입력':s.expected_minutes+'분'}</dd></dl></details>})}</div></section></div></TabsContent>
 <TabsContent value="do"><div className="do-layout"><section className="panel"><div className="section-title"><div><h2>할 일 <span className="count">{allTasks.length}</span></h2><p className="muted">계획을 작게 나누고, 실제로 한 일을 연결하세요.</p></div><button className="button primary" disabled={!selected} onClick={()=>setDialog({kind:'task',newId:crypto.randomUUID()})}><Plus size={16}/>할 일</button></div><div className="search-row"><Search size={18}/><input aria-label="할 일 제목·태그 검색" placeholder="할 일 또는 태그 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters"><Pick label="상태 필터" value={filter} onChange={setFilter} items={[["all","모든 상태"],["open","진행 중"],["done","완료"],["late","지연"],["blocked","막힘"]]}/><Pick label="우선순위 필터" value={prio} onChange={setPrio} items={[["all","모든 우선순위"],...priorityItems]}/><Pick label="정렬" value={sort} onChange={setSort} items={[["due","마감일 빠른 순"],["priority","우선순위 높은 순"],["created","생성일 오래된 순"]]}/><input className="tag-filter" aria-label="태그 필터" placeholder="태그로 거르기" value={tag} onChange={e=>setTag(e.target.value)}/></div><p className="sort-note">동률은 생성 시각 → ID 오름차순 · 미입력 마감일/우선순위는 마지막</p>
 <div className="task-list">{visible.map((t:Row)=><article className={'task-card '+(t.status==='done'?'completed':'')} key={t.id}><button className={'complete-toggle '+(t.status==='done'?'checked':'')} disabled={saving} aria-label={t.title+(t.status==='done'?' 완료 되돌리기':' 완료하기')} onClick={()=>action({action:t.status==='done'?'reopen':'complete',id:t.id},false)}>{t.status==='done'?<Check size={17}/>:null}</button><div className="task-body">{taskView(t)}<div className="task-meta"><span className={'pill '+(t.priority||'')}>{priorityNames[t.priority]||'우선순위 미입력'}</span><span className={t.status==='open'&&t.due_date&&t.due_date<data.today?'late':''}>{t.due_date||'마감일 미입력'}</span><span><Clock3 size={13}/>{t.expected_minutes==null?'예상 미입력':t.expected_minutes+'분 예상'}</span>{JSON.parse(t.tags).map((s:string)=><span className="tag" key={s}>#{s}</span>)}</div></div><button className="button small light" onClick={()=>openLog(t)}>기록</button><button className="icon-button" aria-label={t.title+' 수정'} onClick={()=>setDialog({kind:'task',item:t})}><Pencil size={16}/></button></article>)}{!visible.length&&<div className="empty-panel">조건에 맞는 할 일이 없습니다.</div>}</div></section>
 <aside className="panel timeline-panel"><div className="section-title"><h2>실제로 한 일</h2><span className="count">{sortedLogs.length}건</span></div><div className="total-time"><span>기록한 시간</span><strong>{hours(sortedLogs.reduce((s:number,l:Row)=>s+l.actual_minutes,0))}</strong></div><div className="timeline">{sortedLogs.map((l:Row)=><button className="timeline-item" key={l.id} onClick={()=>setDialog({kind:'detail',item:allTasks.find((t:Row)=>t.id===l.task_id)})}><span className="timeline-date">{localTime(l.started_at)}</span><strong>{allTasks.find((t:Row)=>t.id===l.task_id)?.title}</strong><span className="timeline-duration">{l.actual_minutes}분 <ArrowUpRight size={14}/></span>{l.blocker&&<span className="blocker">막힘 · {l.blocker}</span>}</button>)}{!sortedLogs.length&&<p className="muted">할 일의 ‘기록’을 눌러 첫 실행을 남겨보세요.</p>}</div></aside></div></TabsContent>
 <TabsContent value="see"><section className="panel"><div className="section-title"><div><h2>계획과 실제, 얼마나 달랐나요?</h2><p className="muted">숫자를 누르면 그 숫자가 나온 기록을 볼 수 있습니다.</p></div></div><div className="period"><Field label="마감일 시작"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="마감일 끝"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><button className="button light" onClick={()=>{setFrom('');setTo('')}}>전체 기간</button></div><p className="sort-note">선택한 계획의 삭제되지 않은 할 일 · 기간은 마감일 기준 · 실제 시간은 해당 할 일에 연결된 모든 실행 기록 합계</p>{from&&to&&from>to&&<p className="error-banner">기간의 시작일이 종료일보다 늦습니다.</p>}<div className="metric-grid">{[['tasks','계획 수',summary.tasks.length,'개'],['done','완료',summary.done.length,'개'],['delayed','지연',summary.delayed.length,'개'],['blocked','막힘',summary.blocked.length,'개'],['expected','예상 시간',summary.expected,'분'],['actual','실제 시간',summary.actual,'분'],['difference','실제 − 예상',summary.difference,'분']].map(([key,label,n,unit])=><button className={'metric metric-'+key} key={key} onClick={()=>setDialog({kind:'drill',metric:key,label})}><span>{label}<ArrowUpRight size={15}/></span><strong>{n}<small>{unit}</small></strong></button>)}</div>{summary.unknownEstimates>0&&<p className="setup-inline">예상 시간이 미입력인 할 일 {summary.unknownEstimates}개는 합계에서 0으로 계산했습니다. 실제 계획의 예상 시간을 입력한 뒤 차이를 해석해 주세요.</p>}<div className="time-compare"><div><span>예상</span><div className="bar-track"><div style={{width:`${summary.expected/Math.max(summary.actual,summary.expected,1)*100}%`}}/></div><b>{summary.expected}분</b></div><div><span>실제</span><div className="bar-track actual"><div style={{width:`${summary.actual/Math.max(summary.actual,summary.expected,1)*100}%`}}/></div><b>{summary.actual}분</b></div></div></section><section className="panel reflection-panel"><div><p className="eyebrow">다음 계획으로 이어가기</p><h2>이번에 배운 한 가지는?</h2><p className="muted">고칠 점을 한 줄로 남기고 다음 계획에 가져가세요.</p></div><button className="button primary" disabled={!selected} onClick={()=>setDialog({kind:'reflect',newId:crypto.randomUUID(),reflectionId:crypto.randomUUID()})}>돌아보기로 다음 계획 만들기</button>{data.reflections.filter((r:Row)=>r.plan_id===selected).map((r:Row)=><div className="insight" key={r.id}><p>{r.insight}</p><button className="text-button" onClick={()=>{setSelected(r.next_plan_id);setTab('plan')}}>연결된 다음 계획 보기 <ChevronRight size={15}/></button></div>)}</section></TabsContent></Tabs>
 </>}
 <footer><span>Plan → Do → See → 다음 Plan</span><span>모든 자료는 서버에 저장됩니다. 공개 링크에서는 다른 방문자도 편집할 수 있습니다.</span></footer></main>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!saving){setDialog(null);setError('')}}}><DialogContent className="pds-dialog"><DialogHeader><DialogTitle>{({plan:dialog?.item?'계획 수정':'새 계획',task:dialog?.item?'할 일 수정':'새 할 일',log:'실제로 한 일 기록',detail:dialog?.item?.title,drill:dialog?.label+'의 근거 기록',reflect:'돌아보기와 다음 계획'} as Row)[dialog?.kind]}</DialogTitle><DialogDescription>{dialog?.kind==='log'?'시간은 서울 시간 기준입니다. 실제 시간은 분 단위로 저장됩니다.':dialog?.kind==='detail'?'계획 값과 실행 기록은 별도로 보존됩니다.':'저장한 내용은 이 공개 다이어리 방문자에게 보입니다.'}</DialogDescription></DialogHeader>
 {dialog&&['plan','task','log','reflect'].includes(dialog.kind)&&<form onSubmit={submit} key={dialog.kind+(dialog.item?.id||dialog.newId)} className="edit-form">{dialog.kind==='reflect'&&<Field label="이번 돌아보기에서 다음 계획으로 가져갈 개선점"><textarea name="insight" required maxLength={2000} placeholder="예: 다음 작업 전에는 실행 환경과 저장소 권한부터 확인하기"/></Field>}
 {['plan','reflect'].includes(dialog.kind)&&<><Field label="계획 제목"><input name="title" required maxLength={200} defaultValue={dialog.item?.title||''}/></Field><div className="two-cols"><Field label="시작일"><input name="start_date" type="date" required defaultValue={dialog.item?.start_date||data.today}/></Field><Field label="종료일"><input name="end_date" type="date" required defaultValue={dialog.item?.end_date||data.today}/></Field></div><Field label="성공 기준"><textarea name="success" required maxLength={2000} defaultValue={dialog.item?.success||''} placeholder="완료 여부를 확인할 수 있는 기준을 적어주세요"/></Field><div className="two-cols"><Field label="우선순위"><Pick name="priority" label="우선순위 선택" defaultValue={dialog.item?.priority||'medium'} items={priorityItems}/></Field><Field label="계획 전체 예상 시간 (분)"><input name="expected_minutes" type="number" min="0" max="525600" required defaultValue={dialog.item?.expected_minutes??''}/></Field></div><p className="muted">수정 전 계획은 수정 이력에 남습니다. 계획 전체 예상과 할 일 예상 합계는 별도 값입니다.</p></>}
 {dialog.kind==='task'&&<><Field label="할 일"><input name="title" required maxLength={200} defaultValue={dialog.item?.title||''}/></Field><div className="two-cols"><Field label="마감일"><input name="due_date" type="date" required defaultValue={dialog.item?.due_date||data.today}/></Field><Field label="우선순위"><Pick name="priority" label="우선순위 선택" defaultValue={dialog.item?.priority||'medium'} items={priorityItems}/></Field></div><Field label="태그 (쉼표로 구분)"><input name="tags" maxLength={350} placeholder="면접, 독서, ALEPH" defaultValue={dialog.item?JSON.parse(dialog.item.tags).join(', '):''}/></Field><Field label="예상 시간 (분)"><input name="expected_minutes" type="number" min="0" max="525600" required defaultValue={dialog.item?.expected_minutes??''}/></Field></>}
 {dialog.kind==='log'&&<><div className="two-cols"><Field label="시작 시각 (KST)"><input type="datetime-local" required value={logStart} onChange={e=>setLogStart(e.target.value)}/></Field><Field label="종료 시각 (KST)"><input type="datetime-local" required value={logEnd} onChange={e=>setLogEnd(e.target.value)}/></Field></div><Field label="실제로 작업한 시간 (분)"><input name="actual_minutes" type="number" min="0" max="525600" required placeholder="쉬는 시간은 제외할 수 있습니다"/></Field><Field label="막힌 이유 (없으면 비워두세요)"><textarea name="blocker" maxLength={2000}/></Field><Field label="저장 후 상태"><Pick name="finish" label="상태 선택" defaultValue="no" items={[["no","현재 상태 유지"],["yes","할 일 완료로 변경"]]}/></Field></>}
 {error&&<p role="alert" className="error-banner">{error}</p>}<div className="form-actions"><button type="button" className="button light" disabled={saving} onClick={()=>setDialog(null)}>취소</button><button className="button primary" disabled={saving}>{saving?'저장 중…':'서버에 저장'}</button></div></form>}
 {dialog?.kind==='detail'&&dialog.item&&<><dl className="detail-grid"><dt>할 일 ID</dt><dd>{dialog.item.id}</dd><dt>마감일</dt><dd>{dialog.item.due_date||'미입력'}</dd><dt>예상 시간</dt><dd>{dialog.item.expected_minutes==null?'미입력':dialog.item.expected_minutes+'분'}</dd><dt>상태</dt><dd>{dialog.item.status==='done'?'완료':'진행 중'}</dd></dl><h3>연결된 실행 기록</h3>{data.logs.filter((l:Row)=>l.task_id===dialog.item.id).map((l:Row)=><div className="log-detail" key={l.id}><strong>{l.actual_minutes}분</strong><p>{localTime(l.started_at)} ~ {localTime(l.ended_at)}</p><p>막힌 이유: {l.blocker||'없음'}</p><small className="muted">기록 ID: {l.id}</small></div>)}<div className="form-actions"><button className="button danger" onClick={()=>{setRemove(dialog.item);setDialog(null)}}><Trash2 size={16}/>삭제</button><button className="button light" onClick={()=>setDialog({kind:'task',item:dialog.item})}><Pencil size={16}/>수정</button><button className="button primary" onClick={()=>openLog(dialog.item)}>실행 기록 추가</button></div></>}
 {dialog?.kind==='drill'&&<><p className="muted">{from||'전체'} ~ {to||'전체'} · 마감일 기준</p>{['actual','difference'].includes(dialog.metric)&&<><h3>실제 시간의 근거</h3><Table><TableHeader><TableRow><TableHead>할 일 / 시작</TableHead><TableHead>실제</TableHead></TableRow></TableHeader><TableBody>{summary.logs.map((l:Row)=><TableRow key={l.id}><TableCell>{taskView(allTasks.find((t:Row)=>t.id===l.task_id))}<small>{localTime(l.started_at)}</small></TableCell><TableCell>{l.actual_minutes}분</TableCell></TableRow>)}</TableBody></Table></>}{dialog.metric!=='actual'&&<><h3>{dialog.metric==='difference'?'예상 시간의 근거':'대상 할 일'}</h3><Table><TableHeader><TableRow><TableHead>할 일</TableHead><TableHead>예상</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{((['tasks','done','delayed','blocked'].includes(dialog.metric)?(summary as any)[dialog.metric]:summary.tasks) as Row[]).map(t=><TableRow key={t.id}><TableCell>{taskView(t)}{dialog.metric==='blocked'&&data.logs.filter((l:Row)=>l.task_id===t.id&&l.blocker).map((l:Row)=><p className="muted" key={l.id}>{l.blocker}</p>)}</TableCell><TableCell>{t.expected_minutes??'미입력'}</TableCell><TableCell>{t.status==='done'?'완료':'진행 중'}</TableCell></TableRow>)}</TableBody></Table></>}<p className="small-note">삭제된 할 일과 그 실행 기록은 집계에서 제외됩니다. 완료 수는 현재 완료 상태를 셉니다.</p></>}
 </DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>이 할 일을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>‘{remove?.title}’은 목록과 돌아보기 집계에서 제외됩니다. 연결 기록은 전체 내보내기에 보존됩니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={()=>{action({action:'task-delete',id:remove?.id},false);setRemove(null)}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
