import { integer, text, sqliteTable, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const plans=sqliteTable('plans',{id:text('id').primaryKey(),ownerId:text('owner_id').references(()=>users.id),title:text('title').notNull(),startDate:text('start_date'),endDate:text('end_date'),priority:text('priority'),success:text('success').notNull().default(''),expected:integer('expected_minutes'),draft:integer('draft').notNull().default(0),version:integer('version').notNull().default(1),originReflection:text('origin_reflection'),created:text('created_at').notNull(),updated:text('updated_at').notNull()},t=>[index('plans_owner').on(t.ownerId)]);
export const revisions=sqliteTable('plan_revisions',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),version:integer('version').notNull(),snapshot:text('snapshot').notNull(),created:text('created_at').notNull()},t=>[uniqueIndex('revision_plan_version').on(t.planId,t.version)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),title:text('title').notNull(),due:text('due_date'),priority:text('priority'),tags:text('tags').notNull().default('[]'),expected:integer('expected_minutes'),status:text('status').notNull().default('open'),created:text('created_at').notNull(),updated:text('updated_at').notNull(),deleted:text('deleted_at')},t=>[index('tasks_plan_active').on(t.planId,t.deleted)]);
export const logs=sqliteTable('execution_logs',{id:text('id').primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),requestKey:text('request_key').notNull(),start:text('started_at').notNull(),end:text('ended_at').notNull(),actual:integer('actual_minutes').notNull(),blocker:text('blocker').notNull().default(''),created:text('created_at').notNull()},t=>[uniqueIndex('log_request_unique').on(t.requestKey),index('logs_task').on(t.taskId)]);
export const completions=sqliteTable('completions',{taskId:text('task_id').primaryKey().references(()=>tasks.id),active:integer('active').notNull().default(1),completed:text('completed_at').notNull()});
export const reflections=sqliteTable('reflections',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),insight:text('insight').notNull(),nextPlanId:text('next_plan_id').notNull().references(()=>plans.id),created:text('created_at').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});

export const users=sqliteTable('auth_users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),passwordHash:text('password_hash').notNull(),created:text('created_at').notNull()});
export const sessions=sqliteTable('auth_sessions',{hash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expires:text('expires_at').notNull(),created:text('created_at').notNull()},t=>[index('sessions_user').on(t.userId)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),reset:text('reset_at').notNull()});
export const observations=sqliteTable('observations',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),date:text('date').notNull(),ordinal:integer('ordinal').notNull(),baseline:text('baseline').notNull(),expected:integer('expected').notNull(),actual:integer('actual'),metric:integer('metric'),note:text('note').notNull().default(''),started:text('started_at').notNull(),finished:text('finished_at')},t=>[uniqueIndex('obs_user_date').on(t.userId,t.date),uniqueIndex('obs_user_ordinal').on(t.userId,t.ordinal)]);
export const observationRules=sqliteTable('observation_rules',{userId:text('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),spec:text('spec').notNull(),created:text('created_at').notNull(),change:text('change_json')});

export const observationCancellations=sqliteTable('observation_cancellations',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),dayId:text('day_id').notNull().unique(),original:text('original_json').notNull(),reason:text('reason').notNull(),cancelled:text('cancelled_at').notNull()},t=>[index('obs_cancel_user').on(t.userId)]);
